/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_glvulkantest_Native */

#ifndef _Included_com_example_glvulkantest_Native
#define _Included_com_example_glvulkantest_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_glvulkantest_Native
 * Method:    create
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;II)J
 */
JNIEXPORT jlong JNICALL Java_com_example_glvulkantest_Native_create
  (JNIEnv *, jclass, jobject, jobject, jint, jint);

/*
 * Class:     com_example_glvulkantest_Native
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_glvulkantest_Native_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_glvulkantest_Native
 * Method:    resize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_example_glvulkantest_Native_resize
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_example_glvulkantest_Native
 * Method:    draw
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_glvulkantest_Native_draw
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
